const DB='plantwatch.state.v3',KEY='plantwatch-gemini-key';
const LEGACY_KEYS=['plantwatch.state','plantwatch-v28','plantwatch-v27','plantwatch-v26','plantwatch-v25','plantwatch-v24','plantwatch-v23','plantwatch-v22','plantwatch-v21','plantwatch-v20','plantAlmanac.qa.state.v16','plantAlmanac.state','plant-watch-state'];
const DEF={location:{zip:'75072',label:'McKinney, TX 75072',lat:33.1976,lon:-96.6398},plants:[],water:[],alertsDone:[]};
let state=loadMergedState(),weather=null,cal='today',seasonRange=true;
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
function parseJSON(v){try{return JSON.parse(v)}catch{return null}}
function clone(x){try{return structuredClone(x)}catch{return JSON.parse(JSON.stringify(x))}}
function validState(x){return x&&typeof x==='object'&&(Array.isArray(x.plants)||Array.isArray(x.water)||x.location)}
function normName(s){return String(s||'').trim().toLowerCase().replace(/\s+/g,' ')}
function plantKey(p){return p?.id?`id:${p.id}`:`n:${normName(p?.name)}|${normName(p?.sci||p?.scientificName)}|${p?.start||p?.dateInGround||p?.monitoringSince||''}`}
function richness(o){if(!o||typeof o!=='object')return 0;let n=0;for(const [k,v] of Object.entries(o)){if(v==null||v===''||v===false)continue;n+=typeof v==='object'?2:1}return n}
function deepMergeRich(a,b){if(!a)return clone(b);if(!b)return clone(a);let out=clone(richness(a)>=richness(b)?a:b),other=richness(a)>=richness(b)?b:a;for(const [k,v] of Object.entries(other)){if(v==null||v==='')continue;if(out[k]==null||out[k]==='')out[k]=clone(v);else if(typeof out[k]==='object'&&!Array.isArray(out[k])&&typeof v==='object'&&!Array.isArray(v))out[k]=deepMergeRich(out[k],v)}return out}
function normalizePlant(p){let x=clone(p||{});x.id=x.id||crypto.randomUUID?.()||String(Date.now()+Math.random());x.name=x.name||x.commonName||x.plantName||'Unnamed plant';x.sci=x.sci||x.scientificName||x.botanicalName||'';x.placement=x.placement||x.locationType||x.status||'Outdoors';x.culture=x.culture||x.growingMethod||x.containerType||'Container';x.start=x.start||x.monitoringSince||x.dateInGround||x.plantedDate||'';x.notes=x.notes||x.userNotes||'';x.imageUrl=x.imageUrl||x.photoUrl||x.image||'';return x}
function collectStateCandidates(){let keys=new Set([DB,...LEGACY_KEYS]);for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i);if(k&&(/plant/i.test(k)||/garden/i.test(k)))keys.add(k)}let out=[];for(const k of keys){let v=parseJSON(localStorage.getItem(k)||'null');if(validState(v))out.push({k,v})}return out}
function mergeStates(cands){let result=clone(DEF),pm=new Map(),wm=new Map(),bestLoc=null,bestLocScore=-1;for(const {v} of cands){let loc=v.location||v.settings?.location;if(loc){let s=Object.values(loc).filter(Boolean).length;if(s>bestLocScore){bestLoc=loc;bestLocScore=s}}let plants=Array.isArray(v.plants)?v.plants:Array.isArray(v.specimens)?v.specimens:[];for(let raw of plants){let p=normalizePlant(raw),k=plantKey(p),old=pm.get(k);pm.set(k,old?deepMergeRich(old,p):p)}let water=Array.isArray(v.water)?v.water:Array.isArray(v.irrigation)?v.irrigation:[];for(let w of water){let k=w.id||`${w.plantId||''}|${w.date||''}|${w.amount||w.inches||''}`;if(!wm.has(k))wm.set(k,clone(w))}if(Array.isArray(v.alertsDone))result.alertsDone=[...new Set([...result.alertsDone,...v.alertsDone])]}result.location=Object.assign({},DEF.location,bestLoc||{});result.plants=[...pm.values()];result.water=[...wm.values()].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));return result}
function loadMergedState(){let c=collectStateCandidates(),merged=mergeStates(c);localStorage.setItem(DB,JSON.stringify(merged));return merged}
function save(){localStorage.setItem(DB,JSON.stringify(state))}
function forceRecover(){let before=state.plants.length;state=mergeStates(collectStateCandidates());save();render();$('#migrationStatus').textContent=`Recovery scan complete. ${state.plants.length} plant${state.plants.length===1?'':'s'} available${state.plants.length>before?` (${state.plants.length-before} recovered)`:''}.`;toast('Saved data scan complete')}
function iso(d=new Date()){return d.toISOString().slice(0,10)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(m){let t=$('#toast');t.textContent=m;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2600)}
function uid(){return crypto.randomUUID?.()||String(Date.now()+Math.random())}
function go(v){$$('.view').forEach(x=>x.classList.toggle('on',x.id===v));$$('.nav button').forEach(x=>x.classList.toggle('on',x.dataset.v===v));if(v==='calendar')renderCalendar()}
$$('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.v));$$('[data-cal]').forEach(b=>b.onclick=()=>{cal=b.dataset.cal;$$('[data-cal]').forEach(x=>x.classList.toggle('on',x===b));renderCalendar()});
function monthName(){return new Date().toLocaleDateString(undefined,{month:'long'}).toUpperCase()}
function season(){let m=new Date().getMonth()+1;return m<=2||m===12?'Winter':m<=5?'Spring':m<=8?'Summer':'Autumn'}
function wi(c,night=false){if(night&&c<=3)return'☾';if(c===0)return'☀️';if(c<=3)return'⛅️';if(c===45||c===48)return'🌫️';if(c>=51&&c<=67)return'🌧️';if(c>=71&&c<=77)return'❄️';if(c>=80&&c<=82)return'🌦️';if(c>=95)return'⛈️';return'☁️'}
function cond(c){if(c===0)return'Sunny';if(c<=3)return'Partly cloudy';if(c===45||c===48)return'Fog';if(c>=51&&c<=67)return'Rain';if(c>=71&&c<=77)return'Snow';if(c>=80&&c<=82)return'Showers';if(c>=95)return'Thunderstorms';return'Cloudy'}
async function refreshWeather(){let l=state.location;try{let u=`https://api.open-meteo.com/v1/forecast?latitude=${encodeURIComponent(l.lat)}&longitude=${encodeURIComponent(l.lon)}&current=temperature_2m,relative_humidity_2m,weather_code,precipitation&hourly=temperature_2m,weather_code,precipitation_probability,relative_humidity_2m&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum,precipitation_probability_max,sunrise,sunset&temperature_unit=fahrenheit&precipitation_unit=inch&timezone=auto&forecast_days=7`;let r=await fetch(u);if(!r.ok)throw Error();weather=await r.json();renderToday()}catch{weather=null;$('#summary').textContent='Weather unavailable';$('#hourly').innerHTML='';$('#forecast').innerHTML=''}}
function heroState(){let h=new Date().getHours(),night=h<6||h>=20,c=weather?.current?.weather_code||0,t=weather?.current?.temperature_2m||0,s=season().toLowerCase();let cls=['hero',s,night?'night':'day'];if(c>=51&&c<=82)cls.push('rain');if(c>=95)cls.push('storm');if(c>=71&&c<=77)cls.push('snow');if(t>=98)cls.push('hot');$('#hero').className=cls.join(' ')}
function renderToday(){let l=state.location;$('#todaySub').textContent=l.label;$('#loc').textContent=l.label;$('#plantCount').textContent=state.plants.length;$('#seasonLabel').textContent=`${monthName()} · ${season().toUpperCase()}`;heroState();if(!weather)return;let c=weather.current,d=weather.daily;$('#temp').textContent=Math.round(c.temperature_2m)+'°';$('#humidity').textContent=Math.round(c.relative_humidity_2m)+'%';$('#hiLo').textContent=Math.round(d.temperature_2m_max[0])+'° / '+Math.round(d.temperature_2m_min[0])+'°';let r7=d.precipitation_sum.reduce((a,b)=>a+(b||0),0);$('#rain7').textContent=r7.toFixed(2)+' in';$('#summary').textContent=`${cond(c.weather_code)} · High ${Math.round(d.temperature_2m_max[0])}° · Low ${Math.round(d.temperature_2m_min[0])}° · ${Math.round(d.precipitation_probability_max[0]||0)}% rain`;let now=Date.now(),start=weather.hourly.time.findIndex(t=>new Date(t).getTime()>=now-1800000);if(start<0)start=0;$('#hourly').innerHTML=weather.hourly.time.slice(start,start+24).map((t,j)=>{let i=start+j,h=new Date(t),night=h.getHours()<6||h.getHours()>=20;return`<div class="hour"><span>${j===0?'Now':h.toLocaleTimeString([], {hour:'numeric'})}</span><i>${wi(weather.hourly.weather_code[i],night)}</i><b>${Math.round(weather.hourly.temperature_2m[i])}°</b><em>${Math.round(weather.hourly.precipitation_probability[i]||0)}%</em></div>`}).join('');$('#forecast').innerHTML=d.time.map((t,i)=>`<div class="day"><strong>${new Date(t+'T12:00').toLocaleDateString(undefined,{weekday:'short'})}</strong><div class="ico">${wi(d.weather_code[i])}</div><div class="temps">${Math.round(d.temperature_2m_max[i])}° / ${Math.round(d.temperature_2m_min[i])}°</div><div class="rain">${Math.round(d.precipitation_probability_max[i]||0)}% rain</div></div>`).join('');renderAlerts()}
function markAlertDone(id){state.alertsDone=state.alertsDone||[];if(state.alertsDone.includes(id))state.alertsDone=state.alertsDone.filter(x=>x!==id);else state.alertsDone.push(id);save();renderAlerts()}
function renderAlerts(){if(!weather)return;let d=weather.daily,min=Math.min(...d.temperature_2m_min),max=Math.max(...d.temperature_2m_max),r=d.precipitation_sum.reduce((a,b)=>a+(b||0),0),a=[];let profiled=state.plants.filter(p=>p.profile),coldCount=profiled.filter(p=>min<=(p.profile?.protectBelow??p.profile?.coldProtectF??40)).length,heatCount=profiled.filter(p=>max>=(p.profile?.heatStress??p.profile?.heatStressF??95)).length;if(min<=32)a.push(['freeze','#ff453a','Freeze risk',`Forecast low reaches ${Math.round(min)}°. ${coldCount||'Cold-sensitive'} plant${coldCount===1?'':'s'} may need protection.`]);else if(min<=40)a.push(['cold','#ff9f0a','Cold watch',`Forecast low reaches ${Math.round(min)}°. Review tropical and container plants.`]);if(max>=100)a.push(['heat','#ff453a','Severe heat risk',`Forecast high reaches ${Math.round(max)}°. ${heatCount||'Vulnerable'} plant${heatCount===1?'':'s'} may need shade or extra moisture.`]);else if(max>=95)a.push(['heat','#ff9f0a','Heat stress',`Forecast high reaches ${Math.round(max)}°. Review containers and newly established plants.`]);if(r<.15)a.push(['dry','#0a84ff','Dry 7-day outlook',`Only ${r.toFixed(2)} in of rain is forecast this week.`]);if(!a.length)a.push(['clear','#34c759','No immediate hazards','No major cold, heat, or drought trigger is visible in the 7-day forecast.']);let done=state.alertsDone||[];$('#alerts').innerHTML=a.map(x=>`<div class="card alert ${done.includes(x[0])?'alertDone':''}" style="--c:${x[1]}" onclick="markAlertDone('${x[0]}')"><h3>${x[2]}</h3><p>${x[3]} ${done.includes(x[0])?'✓ Checked off':'Tap to check off.'}</p></div>`).join('');$('#risk').textContent=a[0][2]+' · '+state.plants.length+' plants monitored'}
function toggleAdd(){$('#addPlant').classList.toggle('hidden');$('#pd').value=$('#pd').value||iso()}
function addPlant(){let n=$('#pn').value.trim();if(!n)return toast('Enter a plant name');let p=normalizePlant({id:uid(),name:n,sci:$('#ps').value.trim(),placement:$('#pp').value,culture:$('#pc').value,start:$('#pd').value||iso(),imageUrl:$('#pi').value.trim(),notes:$('#pnotes').value.trim()});state.plants=Array.isArray(state.plants)?state.plants:[];state.plants.unshift(p);save();$('#pn').value='';$('#ps').value='';$('#pi').value='';$('#pnotes').value='';$('#addPlant').classList.add('hidden');render();toast('Plant added')}
function removePlant(id){if(!confirm('Remove this plant from monitoring?'))return;state.plants=state.plants.filter(p=>p.id!==id);save();render();toast('Plant removed')}
function plantProfileValue(p,keys,def='—'){for(let k of keys){let v=p.profile?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return def}
function fmtF(v){if(v==='—')return v;return String(v).includes('°')?String(v):`${v}°F`}
function plantCard(p){let has=!!p.profile,protect=plantProfileValue(p,['protectBelow','coldProtectF','protectBelowF']),cold=plantProfileValue(p,['coldDamage','coldDamageF']),heat=plantProfileValue(p,['heatStress','heatStressF']),severe=plantProfileValue(p,['severeHeat','severeHeatF']),drought=plantProfileValue(p,['droughtTriggerDays','droughtDays']),weekly=plantProfileValue(p,['weeklyWaterInches','weeklyWater','waterPerWeek']);let care=p.profile?.locationNotes||p.profile?.careSummary||p.profile?.notes||p.notes||'';let img=p.imageUrl?`style="background-image:url('${esc(p.imageUrl)}')"`:'';return `<div class="card plantCard"><div class="plantVisual ${p.imageUrl?'hasImage':''}" ${img}><div class="plantVisualLabel">${p.imageUrl?'Reference image':'Add a photo or reference image'}</div></div><div class="plantBody"><h3>${esc(p.name)}</h3>${p.sci?`<p class="sci">${esc(p.sci)}</p>`:''}<p class="meta">${esc(p.placement||'Outdoors')} · ${esc(p.culture||'Container')} · monitoring since ${esc(p.start||'—')}</p><span class="badge">${has?'Monitoring profile saved':'Research needed'}</span>${has?`<div class="profileGrid"><div><span>Protect below</span><b>${fmtF(protect)}</b></div><div><span>Cold damage</span><b>${fmtF(cold)}</b></div><div><span>Heat stress</span><b>${fmtF(heat)}</b></div><div><span>Severe heat</span><b>${fmtF(severe)}</b></div><div><span>Drought trigger</span><b>${drought==='—'?'—':`${drought} days`}</b></div><div><span>Weekly water</span><b>${weekly==='—'?'—':String(weekly).match(/in/) ? esc(weekly):`${esc(weekly)} in`}</b></div></div>`:`<button class="secondary full" style="margin-top:13px" onclick="researchPlant('${p.id}')">Research monitoring specs</button>`}${care?`<p class="careText">${esc(care)}</p>`:''}<button class="detailToggle" onclick="togglePlantDetail('${p.id}')">Care details</button><div id="detail-${p.id}" class="detailPane hidden"><h4>Notes & care</h4><p>${esc(p.notes||care||'No additional notes saved yet.')}</p></div><div class="cardActions"><button class="secondary" onclick="quickWater('${p.id}')">Watered</button><button class="danger" onclick="removePlant('${p.id}')">Remove</button></div></div></div>`}
function togglePlantDetail(id){$('#detail-'+id)?.classList.toggle('hidden')}
function renderPlants(){let q=($('#plantSearch')?.value||'').toLowerCase(),p=state.plants.filter(x=>(x.name+' '+(x.sci||'')).toLowerCase().includes(q));$('#plantCount').textContent=state.plants.length;$('#plantList').innerHTML=p.length?p.map(plantCard).join(''):'<div class="card empty">No plants yet.</div>';$('#waterPlant').innerHTML='<option value="">Whole yard</option>'+state.plants.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}
async function researchPlant(id){let p=state.plants.find(x=>x.id===id),key=localStorage.getItem(KEY)||localStorage.getItem('plantAlmanac.geminiKey')||'';if(!p)return;if(!key){toast('Save your Gemini API key in More first');go('more');return}toast(`Researching ${p.name}…`);let prompt=`Return JSON only for this plant in ${state.location.label}: ${p.name}${p.sci?` (${p.sci})`:''}. Fields: scientificName, protectBelowF, coldDamageF, heatStressF, severeHeatF, droughtTriggerDays, weeklyWaterInches, locationNotes, seasonal object with optional windows formatted MM-DD as {start,end} for fertilize, prune, flowering, fruiting, harvest, moveInside, moveOutside, transplantOutside, directSow. Use horticulturally conservative thresholds appropriate to the plant and local climate.`;let models=['gemini-2.5-flash','gemini-2.5-flash-lite'];let lastErr='';for(let model of models){try{let r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json'}})});if(!r.ok){lastErr=`${r.status} ${await r.text()}`;continue}let j=await r.json(),txt=j.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||'',profile=parseJSON(txt);if(!profile)throw Error('Invalid JSON');p.profile=Object.assign({},p.profile||{},profile);p.sci=p.sci||profile.scientificName||'';save();render();toast('Monitoring profile saved');return}catch(e){lastErr=String(e)}}toast('Research temporarily unavailable. Your plant was kept safely.');console.warn(lastErr)}
function quickWater(id){state.water.unshift({id:uid(),plantId:id,date:iso(),amount:.5});save();renderWater();toast('Watering logged')}
function logWater(){state.water.unshift({id:uid(),plantId:$('#waterPlant').value,date:$('#waterDate').value||iso(),amount:+$('#waterAmount').value||0});save();renderWater();toast('Watering logged')}
function renderWater(){$('#waterDate').value=$('#waterDate').value||iso();let nm=Object.fromEntries(state.plants.map(p=>[p.id,p.name]));$('#waterList').innerHTML=state.water.length?state.water.slice(0,30).map(w=>`<div class="card"><b>${esc(nm[w.plantId]||'Whole yard')}</b><p class="sub">${esc(w.date)} · ${(+w.amount||0).toFixed(2)} in equivalent</p></div>`).join(''):'<div class="card empty">No watering activity logged yet.</div>'}
function tasks(){let out=[];state.plants.forEach(p=>{let s=p.profile?.seasonal||{};[['fertilize','🧪','Fertilize'],['prune','✂️','Prune / maintenance'],['flowering','🌸','Flowering'],['fruiting','🍎','Fruiting'],['harvest','🧺','Harvest'],['moveInside','🏠','Move inside / protect'],['moveOutside','☀️','Move outside']].forEach(([k,ic,label])=>{let w=s[k];if(w?.start){let yr=new Date().getFullYear();out.push({date:`${yr}-${w.start}`,icon:ic,title:`${label} · ${p.name}`})}})});return out.sort((a,b)=>a.date.localeCompare(b.date))}
function renderTasks(a){return a.length?a.map(t=>`<div class="card task"><div class="taskIcon">${t.icon}</div><div><b>${esc(t.title)}</b><p class="sub">${t.date}</p></div></div>`).join(''):'<div class="card empty">No scheduled plant actions.</div>'}
function pct(mmdd){if(!mmdd)return null;let [m,d]=mmdd.split('-').map(Number),dt=new Date(2026,m-1,d||1),yr=new Date(2026,0,1);return((dt-yr)/(365*864e5))*100}
function bars(p){let s=p.profile?.seasonal||{},defs=[['transplantOutside','planting'],['directSow','planting'],['flowering','bloom'],['fruiting','bloom'],['harvest','harvest'],['fertilize','care'],['prune','care'],['moveInside','move'],['moveOutside','move']];return defs.map(([k,c])=>{let w=s[k];if(!w?.start)return'';let a=pct(w.start),b=pct(w.end||w.start);if(b<a)b=100;return`<span class="bar ${c}" style="left:${a}%;width:${Math.max(.8,b-a+.6)}%"></span>`}).join('')}
function rangeCalendar(){let months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],names=state.plants.map(p=>`<div class="plantName">${esc(p.name)}</div>`).join(''),lanes=state.plants.map(p=>`<div class="lane">${bars(p)}</div>`).join(''),today=new Date(),todayPct=((today-new Date(today.getFullYear(),0,1))/(365*864e5))*100;return`<div class="seasonHero"><div class="month">${monthName()} · ${season()}</div><h3>Your garden this season</h3><p class="sub">${esc(state.location.label)} · ${state.plants.length} plants.</p></div><div class="seasonTabs"><button onclick="seasonRange=false;renderCalendar()">List</button><button class="on" onclick="seasonRange=true;renderCalendar()">Range calendar</button></div><div class="rangeFrame"><div class="rangeNames"><div class="nameHead">Plants</div>${names||'<div class="plantName">No plants</div>'}</div><div id="rangeScroller" class="rangeScroller"><div class="rangeInner"><div class="legend"><span><i style="background:#34c759"></i>Planting</span><span><i style="background:#ff64aa"></i>Bloom / fruit</span><span><i style="background:#f2b705"></i>Harvest</span><span><i style="background:#9b7ede"></i>Care</span><span><i style="background:#4f8bd6"></i>Move / protect</span></div><div class="months">${months.map(x=>`<span>${x}</span>`).join('')}</div><div class="nowLine" style="left:${todayPct}%"></div>${lanes}</div></div></div><div class="rangeNote">Plant names stay pinned while the timeline scrolls. The blue line marks today.</div>`}
function listSeason(){return`<div class="seasonHero"><div class="month">${monthName()} · ${season()}</div><h3>Your garden this season</h3><p class="sub">${esc(state.location.label)} · ${state.plants.length} plants.</p></div><div class="seasonTabs"><button class="on" onclick="seasonRange=false;renderCalendar()">List</button><button onclick="seasonRange=true;renderCalendar()">Range calendar</button></div>${renderTasks(tasks())}`}
function renderCalendar(){let t=tasks(),today=iso(),end=new Date();end.setDate(end.getDate()+7);if(cal==='today')$('#calendarBody').innerHTML=renderTasks(t.filter(x=>x.date===today));else if(cal==='week')$('#calendarBody').innerHTML=renderTasks(t.filter(x=>x.date>=today&&x.date<=iso(end)));else if(cal==='month')$('#calendarBody').innerHTML=renderTasks(t.filter(x=>x.date.slice(0,7)===today.slice(0,7)));else{$('#calendarBody').innerHTML=seasonRange?rangeCalendar():listSeason();if(seasonRange)requestAnimationFrame(()=>{let s=$('#rangeScroller');if(s){let month=80,idx=new Date().getMonth();s.scrollLeft=Math.max(0,idx*month+month/2-s.clientWidth/2)}})}}
function renderMore(){let l=state.location;$('#zip').value=l.zip||'';$('#label').value=l.label||'';$('#lat').value=l.lat;$('#lon').value=l.lon;let k=localStorage.getItem(KEY)||localStorage.getItem('plantAlmanac.geminiKey')||'';$('#gemini').value=k;$('#keyStatus').textContent=k?'✓ API key saved on this iPhone/browser':'No API key saved yet.'}
function saveKey(){let k=$('#gemini').value.trim();if(k)localStorage.setItem(KEY,k);else localStorage.removeItem(KEY);renderMore();toast(k?'API key saved':'API key removed')}
function saveLocation(){state.location={zip:$('#zip').value.trim(),label:$('#label').value.trim()||$('#zip').value.trim(),lat:+$('#lat').value,lon:+$('#lon').value};save();renderMore();refreshWeather();toast('Location saved')}
function render(){renderPlants();renderWater();renderCalendar();renderMore();renderToday()}
render();refreshWeather();setInterval(()=>{if(!document.hidden)refreshWeather()},15*60*1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshWeather()});
