import Foundation

enum DemoGarden {
    static let plants: [Plant] = [
        make("Mikawa Yatsubusa", "Acer palmatum 'Mikawa yatsubusa'", .outdoors, .inGround, climate: ClimateProfile(usdaHardinessZoneMin: 5, usdaHardinessZoneMax: 9, ahsHeatZoneMin: 1, ahsHeatZoneMax: 8, protectBelowF: nil, coldDamageF: -10, lethalColdF: -20, heatStressF: 92, severeHeatF: 100, lethalHeatF: 108, preferredNightMaxF: 70, hotNightStressF: 75, hotNightFailureF: 82, hotNightConsecutiveDays: 10, chillHoursMin: nil, chillHoursMax: nil), shade: true),
        make("Monstera Thai Constellation", "Monstera deliciosa 'Thai Constellation'", .outdoors, .container, climate: ClimateProfile(usdaHardinessZoneMin: 10, usdaHardinessZoneMax: 12, ahsHeatZoneMin: 1, ahsHeatZoneMax: 12, protectBelowF: 50, coldDamageF: 35, lethalColdF: 30, heatStressF: 95, severeHeatF: 105, lethalHeatF: 112, preferredNightMaxF: 78, hotNightStressF: 82, hotNightFailureF: 90, hotNightConsecutiveDays: 14, chillHoursMin: nil, chillHoursMax: nil), shade: true),
        make("Black Diamond Crape Myrtle", "Lagerstroemia indica hybrid", .outdoors, .inGround, climate: ClimateProfile(usdaHardinessZoneMin: 7, usdaHardinessZoneMax: 10, ahsHeatZoneMin: 7, ahsHeatZoneMax: 12, protectBelowF: nil, coldDamageF: 0, lethalColdF: -10, heatStressF: 102, severeHeatF: 110, lethalHeatF: 118, preferredNightMaxF: 82, hotNightStressF: 86, hotNightFailureF: 92, hotNightConsecutiveDays: 20, chillHoursMin: nil, chillHoursMax: nil), shade: false),
        make("Eclipse Hydrangea", "Hydrangea macrophylla 'Eclipse'", .outdoors, .inGround, climate: ClimateProfile(usdaHardinessZoneMin: 5, usdaHardinessZoneMax: 9, ahsHeatZoneMin: 1, ahsHeatZoneMax: 8, protectBelowF: nil, coldDamageF: -10, lethalColdF: -20, heatStressF: 90, severeHeatF: 98, lethalHeatF: 106, preferredNightMaxF: 72, hotNightStressF: 78, hotNightFailureF: 84, hotNightConsecutiveDays: 10, chillHoursMin: nil, chillHoursMax: nil), shade: true),
        make("Guava", "Psidium guajava", .outdoors, .container, climate: ClimateProfile(usdaHardinessZoneMin: 9, usdaHardinessZoneMax: 11, ahsHeatZoneMin: 7, ahsHeatZoneMax: 12, protectBelowF: 38, coldDamageF: 28, lethalColdF: 22, heatStressF: 100, severeHeatF: 108, lethalHeatF: 116, preferredNightMaxF: 80, hotNightStressF: 84, hotNightFailureF: 90, hotNightConsecutiveDays: 20, chillHoursMin: nil, chillHoursMax: nil), shade: false),
        make("San Pedro Cactus", "Echinopsis pachanoi", .outdoors, .container, climate: ClimateProfile(usdaHardinessZoneMin: 8, usdaHardinessZoneMax: 11, ahsHeatZoneMin: 6, ahsHeatZoneMax: 12, protectBelowF: 35, coldDamageF: 28, lethalColdF: 22, heatStressF: 102, severeHeatF: 110, lethalHeatF: 118, preferredNightMaxF: 78, hotNightStressF: 85, hotNightFailureF: 92, hotNightConsecutiveDays: 20, chillHoursMin: nil, chillHoursMax: nil), shade: false)
    ]

    private static func make(_ name: String, _ sci: String, _ placement: Placement, _ culture: Culture, climate: ClimateProfile, shade: Bool) -> Plant {
        var p = Plant(name: name, scientificName: sci, placement: placement, culture: culture, monitoringSince: Calendar.current.date(byAdding: .month, value: -4, to: Date()) ?? Date())
        p.profile = ResearchProfile(scientificName: sci, climate: climate, water: WaterProfile(weeklyWaterInches: culture == .container ? 1.0 : 0.8, referenceEtCoefficient: culture == .container ? 0.8 : 0.7, droughtTolerance: shade ? "low" : "moderate", waterloggingTolerance: shade ? "low" : "moderate", summerAdjustmentPercent: 20, winterAdjustmentPercent: -20), sun: SunProfile(preferredExposure: shade ? ["Part shade", "Shade"] : ["Full sun"], afternoonShadeRecommended: shade), care: CareProfile(), seasonal: SeasonalProfile(moveOutsideStart: culture == .container ? "04-15" : nil, moveOutsideEnd: culture == .container ? "05-15" : nil, moveInsideStart: culture == .container ? "10-01" : nil, moveInsideEnd: culture == .container ? "11-01" : nil, fertilizeStart: "03-01", fertilizeEnd: "09-30", pruneStart: "02-01", pruneEnd: "03-31", floweringStart: shade ? "05-01" : "06-01", floweringEnd: shade ? "09-15" : "09-30"), biology: BiologyProfile(floweringCapable: true, fruitingCapable: nil, fruitingTypicalInUserContext: nil, harvestRelevant: false, evergreen: nil, deciduous: nil, growthHabit: []))
        return p
    }
}
